import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Button } from "@/components/ui/button";
import { KeyRound, Users, Lightbulb, HelpCircle, ListChecks, Info, Copy, Check } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import type { ResearchAnalysis } from "@/lib/reportTypes";

function diffColor(d: number) {
  if (d <= 30) return "text-success";
  if (d <= 60) return "text-warning";
  return "text-error";
}

function priorityBadge(priority: string) {
  const map: Record<string, string> = {
    high: "bg-error/10 text-error border-error/20",
    medium: "bg-warning/10 text-warning border-warning/20",
    low: "bg-muted text-muted-foreground border-border",
  };
  return map[priority] ?? map.low;
}

export default function ResearchReport({ research }: { research: ResearchAnalysis }) {
  const [copied, setCopied] = useState(false);

  const copySchema = async () => {
    if (!research.faqSchema) return;
    try {
      await navigator.clipboard.writeText(research.faqSchema);
      setCopied(true);
      toast.success("FAQ JSON-LD schema copied to clipboard");
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error("Could not copy. Select the code and copy manually.");
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-2">
        <span className="text-sm text-muted-foreground">Detected niche:</span>
        <Badge variant="outline" className="bg-primary/5 text-primary border-primary/20">{research.detectedNiche}</Badge>
      </div>

      {/* Methodology disclaimer */}
      <div className="flex items-start gap-2.5 p-3 rounded-lg border border-warning/20 bg-warning/5">
        <Info className="w-4 h-4 text-warning shrink-0 mt-0.5" />
        <p className="text-xs text-muted-foreground leading-relaxed">
          <span className="font-semibold text-foreground">AI-estimated metrics.</span> Keyword volume,
          difficulty, opportunity scores and competitor authority below are generated by AI analysis of
          this site and its niche — they are directional guidance, not live data from a keyword/backlink
          provider. Connect a dedicated SEO data source (e.g. DataForSEO, Semrush) for exact figures.
        </p>
      </div>

      {/* Keywords */}
      <Card className="p-6 border border-border bg-card">
        <h3 className="text-lg font-semibold text-foreground mb-5 flex items-center gap-2">
          <KeyRound className="w-5 h-5 text-primary" /> Keyword Opportunities
        </h3>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="text-left text-xs uppercase tracking-wide text-muted-foreground border-b border-border">
                <th className="py-2 pr-4 font-semibold">Keyword</th>
                <th className="py-2 pr-4 font-semibold">Type</th>
                <th className="py-2 pr-4 font-semibold">Intent</th>
                <th className="py-2 pr-4 font-semibold">Volume <span className="normal-case font-normal text-[10px]">(est.)</span></th>
                <th className="py-2 pr-4 font-semibold">Difficulty <span className="normal-case font-normal text-[10px]">(est.)</span></th>
                <th className="py-2 font-semibold">Opportunity <span className="normal-case font-normal text-[10px]">(est.)</span></th>
              </tr>
            </thead>
            <tbody>
              {research.keywords.map((kw, i) => (
                <tr key={i} className="border-b border-border/50 hover:bg-muted/30">
                  <td className="py-3 pr-4 font-medium text-foreground">{kw.keyword}</td>
                  <td className="py-3 pr-4"><Badge variant="outline" className="text-[10px] capitalize bg-primary/5 text-primary border-primary/20">{kw.type}</Badge></td>
                  <td className="py-3 pr-4 capitalize text-muted-foreground">{kw.intent}</td>
                  <td className="py-3 pr-4 text-muted-foreground">{kw.estimatedVolume}</td>
                  <td className={`py-3 pr-4 font-semibold ${diffColor(kw.difficulty)}`}>{kw.difficulty}</td>
                  <td className="py-3">
                    <div className="flex items-center gap-2">
                      <Progress value={kw.opportunityScore} className="h-1.5 w-16" />
                      <span className="text-xs font-semibold text-foreground">{kw.opportunityScore}/100</span>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>

      {/* Competitors */}
      {research.competitors.length > 0 && (
        <Card className="p-6 border border-border bg-card">
          <h3 className="text-lg font-semibold text-foreground mb-5 flex items-center gap-2">
            <Users className="w-5 h-5 text-primary" /> Likely Ranking Competitors
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {research.competitors.map((c, i) => (
              <div key={i} className="p-4 rounded-lg border border-border bg-background">
                <div className="flex items-center justify-between mb-2">
                  <div>
                    <h4 className="font-semibold text-foreground">{c.name}</h4>
                    <p className="text-xs text-muted-foreground">{c.domain}</p>
                  </div>
                  <div className="text-right">
                    <p className="text-xs text-muted-foreground">Authority (est.)</p>
                    <p className="text-lg font-bold text-primary">{c.estimatedAuthority}</p>
                  </div>
                </div>
                <p className="text-sm text-muted-foreground mb-2">{c.strengthSummary}</p>
                {c.keyAdvantages?.length > 0 && (
                  <div className="flex flex-wrap gap-1.5">
                    {c.keyAdvantages.map((a, j) => (
                      <Badge key={j} variant="outline" className="text-[10px] bg-muted text-muted-foreground border-border">{a}</Badge>
                    ))}
                  </div>
                )}
              </div>
            ))}
          </div>
        </Card>
      )}

      {/* Content Gaps */}
      {research.contentGaps.length > 0 && (
        <Card className="p-6 border border-border bg-card">
          <h3 className="text-lg font-semibold text-foreground mb-5 flex items-center gap-2">
            <Lightbulb className="w-5 h-5 text-primary" /> Content Gap Opportunities
          </h3>
          <div className="space-y-3">
            {research.contentGaps.map((g, i) => (
              <div key={i} className="flex items-start gap-3 p-3 rounded-lg border border-border bg-background">
                <Badge variant="outline" className={`capitalize shrink-0 ${priorityBadge(g.priority)}`}>{g.priority}</Badge>
                <div>
                  <h4 className="font-semibold text-foreground text-sm">{g.topic}</h4>
                  <p className="text-sm text-muted-foreground">{g.reason}</p>
                </div>
              </div>
            ))}
          </div>
        </Card>
      )}

      {/* Snippet Opportunities */}
      {research.snippetOpportunities.length > 0 && (
        <Card className="p-6 border border-border bg-card">
          <h3 className="text-lg font-semibold text-foreground mb-5 flex items-center gap-2">
            <ListChecks className="w-5 h-5 text-primary" /> Featured Snippet Opportunities
          </h3>
          <div className="space-y-3">
            {research.snippetOpportunities.map((s, i) => (
              <div key={i} className="p-3 rounded-lg border border-border bg-background">
                <div className="flex items-center gap-2 mb-1">
                  <Badge variant="outline" className="text-[10px] capitalize bg-primary/5 text-primary border-primary/20">{s.format}</Badge>
                  <h4 className="font-semibold text-foreground text-sm">{s.query}</h4>
                </div>
                <p className="text-sm text-muted-foreground">{s.recommendation}</p>
              </div>
            ))}
          </div>
        </Card>
      )}

      {/* FAQ Suggestions */}
      {research.faqSuggestions.length > 0 && (
        <Card className="p-6 border border-border bg-card">
          <div className="flex items-center justify-between mb-5 gap-3 flex-wrap">
            <h3 className="text-lg font-semibold text-foreground flex items-center gap-2">
              <HelpCircle className="w-5 h-5 text-primary" /> FAQ Suggestions
              <Badge variant="outline" className="bg-primary/5 text-primary border-primary/20">{research.faqSuggestions.length}</Badge>
            </h3>
            {research.faqSchema && (
              <Button size="sm" variant="outline" onClick={copySchema} className="gap-1.5">
                {copied ? <Check className="w-3.5 h-3.5 text-success" /> : <Copy className="w-3.5 h-3.5" />}
                {copied ? "Copied" : "Copy JSON-LD schema"}
              </Button>
            )}
          </div>
          <div className="space-y-3">
            {research.faqSuggestions.map((f, i) => (
              <div key={i} className="p-4 rounded-lg border border-border bg-background">
                <h4 className="font-semibold text-foreground text-sm mb-1">{f.question}</h4>
                <p className="text-sm text-muted-foreground">{f.suggestedAnswer}</p>
              </div>
            ))}
          </div>

          {research.faqSchema && (
            <div className="mt-5">
              <p className="text-xs font-semibold text-foreground mb-2">Copy-paste FAQPage JSON-LD (add inside a &lt;script type="application/ld+json"&gt; tag):</p>
              <pre className="text-[11px] leading-relaxed bg-muted/50 border border-border rounded-lg p-4 overflow-x-auto max-h-72 text-muted-foreground">{research.faqSchema}</pre>
            </div>
          )}
        </Card>
      )}
    </div>
  );
}
